#!/usr/bin/bash

CONFIG_FILES="$HOME/.config/hypr/component/waybar/config $HOME/.config/hypr/component/waybar/style.css"

trap "killall waybar" EXIT

while true; do
    waybar -c $HOME/.config/hypr/component/waybar/config -s $HOME/.config/hypr/component/waybar/style.css &
    inotifywait -e create,modify $CONFIG_FILES
    killall waybar
done
